In [19]:
import pandas as pd
alunosDic = {'Nome':['Ricardo', 'Pedro', 'Roberto', 'Carlos'],
         'Nota':[4, 7, 5.5, 9],
         'Aprovado':['Não', 'Sim', 'Não', 'Sim']}

In [22]:
alunosDF = pd.DataFrame(alunosDic)

In [23]:
alunosDF

Nome  Nota Aprovado
0  Ricardo   4.0      Não
1    Pedro   7.0      Sim
2  Roberto   5.5      Não
3   Carlos   9.0      Sim

In [24]:
objeto1 = pd.Series([3, 5, 9, 10, 12])
print(objeto1)

0     3
1     5
2     9
3    10
4    12
dtype: int64


In [25]:
import numpy as np
array1 = np.array([3, 5, 9, 10, 12])
array2 = np.array([(3, 5, 9, 10, 12), (1, 2, 9, 4, 10)])
print(array1)
print(array2)

[ 3  5  9 10 12]
[[ 3  5  9 10 12]
 [ 1  2  9  4 10]]


In [26]:
objeto2 = pd.Series(array1)
print(objeto2)

0     3
1     5
2     9
3    10
4    12
dtype: int32


<h3> O comando pd.Series só pode ser utilizado em arrays unidimensionais

In [27]:
alunosDF

Nome  Nota Aprovado
0  Ricardo   4.0      Não
1    Pedro   7.0      Sim
2  Roberto   5.5      Não
3   Carlos   9.0      Sim

#### Explorando o dataframe

In [28]:
alunosDF.head()

Nome  Nota Aprovado
0  Ricardo   4.0      Não
1    Pedro   7.0      Sim
2  Roberto   5.5      Não
3   Carlos   9.0      Sim

In [29]:
alunosDF.shape # mostra o tamanho (linhas, colunas)

(4, 3)

In [30]:
alunosDF.describe()

Nota
count  4.000000
mean   6.375000
std    2.136001
min    4.000000
25%    5.125000
50%    6.250000
75%    7.500000
max    9.000000

In [31]:
alunosDF

Nome  Nota Aprovado
0  Ricardo   4.0      Não
1    Pedro   7.0      Sim
2  Roberto   5.5      Não
3   Carlos   9.0      Sim

In [38]:
alunosDF['Nome']

0    Ricardo
1      Pedro
2    Roberto
3     Carlos
Name: Nome, dtype: object

In [46]:
alunosDF.loc[[2]] #slice

Nome  Nota Aprovado
2  Roberto   5.5      Não

In [47]:
alunosDF.loc[0:2] #slicing from index 0 to 2

Nome  Nota Aprovado
0  Ricardo   4.0      Não
1    Pedro   7.0      Sim
2  Roberto   5.5      Não

In [48]:
alunosDF.loc[alunosDF['Nome']=='Pedro']

Nome  Nota Aprovado
1  Pedro   7.0      Sim

In [49]:
alunosDF.loc[alunosDF['Nome']=='Carlos']

Nome  Nota Aprovado
3  Carlos   9.0      Sim

In [50]:
alunosDF.loc[alunosDF['Nota'] >= 7]

Nome  Nota Aprovado
1   Pedro   7.0      Sim
3  Carlos   9.0      Sim

In [54]:
alunosDF.loc[alunosDF['Nota'] < 7]

Nome  Nota Aprovado
0  Ricardo   4.0      Não
2  Roberto   5.5      Não

In [55]:
#Estatística dos alunos com nota inferior a 7.
alunosDF.loc[alunosDF['Nota'] < 7].describe()

Nota
count  2.00000
mean   4.75000
std    1.06066
min    4.00000
25%    4.37500
50%    4.75000
75%    5.12500
max    5.50000

In [58]:
alunosDF.loc[alunosDF['Aprovado'] == 'Sim']

Nome  Nota Aprovado
1   Pedro   7.0      Sim
3  Carlos   9.0      Sim

<hr>
<h1> manipulando linhas de dataframes

In [59]:
alunosDF

Nome  Nota Aprovado
0  Ricardo   4.0      Não
1    Pedro   7.0      Sim
2  Roberto   5.5      Não
3   Carlos   9.0      Sim

In [62]:
primeiraslinhas = alunosDF.loc[0:2]

In [63]:
primeiraslinhas

Nome  Nota Aprovado
0  Ricardo   4.0      Não
1    Pedro   7.0      Sim
2  Roberto   5.5      Não

In [64]:
novoDF = alunosDF.loc[alunosDF['Nota'] != 9]

In [65]:
novoDF

Nome  Nota Aprovado
0  Ricardo   4.0      Não
1    Pedro   7.0      Sim
2  Roberto   5.5      Não

In [66]:
alunosReprovados = alunosDF.loc[alunosDF['Aprovado'] != 'Sim']

In [67]:
alunosReprovados

Nome  Nota Aprovado
0  Ricardo   4.0      Não
2  Roberto   5.5      Não

---
<h1> Abrindo e manipulando arquivos externos

In [9]:
import pandas as pd
dados = pd.read_excel('C:/Users/lenon/Desktop/Programação/PythonData/data_science/arquivos_csv/arquivo1.xlsx')

In [12]:
print(type(dados))
dados.head() # dentro do parenteses eu posso colocar a qtd de linhas que serão mostradas

<class 'pandas.core.frame.DataFrame'>


Números Letras
0        1      a
1        2      b
2        3      c
3        4      d
4        5      e

---
<h1> Open a csv file

In [14]:
import pandas as pd
olympic_data  = pd.read_csv('C:/Users/lenon/Desktop/Programação/PythonData/data_science/arquivos_csv/athlete_events.csv')

In [20]:
print(f'A variável é {type(olympic_data)}')
olympic_data.head(4) #show the first 4 lines

A variável é <class 'pandas.core.frame.DataFrame'>


ID                  Name Sex   Age  Height  Weight            Team  NOC  \
0   1             A Dijiang   M  24.0   180.0    80.0           China  CHN   
1   2              A Lamusi   M  23.0   170.0    60.0           China  CHN   
2   3   Gunnar Nielsen Aaby   M  24.0     NaN     NaN         Denmark  DEN   
3   4  Edgar Lindenau Aabye   M  34.0     NaN     NaN  Denmark/Sweden  DEN   

         Games  Year  Season       City       Sport  \
0  1992 Summer  1992  Summer  Barcelona  Basketball   
1  2012 Summer  2012  Summer     London        Judo   
2  1920 Summer  1920  Summer  Antwerpen    Football   
3  1900 Summer  1900  Summer      Paris  Tug-Of-War   

                          Event Medal  
0   Basketball Men's Basketball   NaN  
1  Judo Men's Extra-Lightweight   NaN  
2       Football Men's Football   NaN  
3   Tug-Of-War Men's Tug-Of-War  Gold

In [24]:
olympic_data.rename(columns={'Name': 'Nome', 'Sex': 'Sexo', 'Age': 'Idade'}, inplace = True)
#inplace = True -> serv

In [26]:
altura = olympic_data['Height']

In [27]:
type(altura)

pandas.core.series.Series

In [28]:
print(altura)

0         180.0
1         170.0
2           NaN
3           NaN
4         185.0
          ...  
271111    179.0
271112    176.0
271113    176.0
271114    185.0
271115    185.0
Name: Height, Length: 271116, dtype: float64


In [29]:
olympic_data['Medal'].value_counts()

Gold      13372
Bronze    13295
Silver    13116
Name: Medal, dtype: int64

In [30]:
olympic_data['City'].value_counts()

London                    22426
Athina                    15556
Sydney                    13821
Atlanta                   13780
Rio de Janeiro            13688
Beijing                   13602
Barcelona                 12977
Los Angeles               12423
Seoul                     12037
Munich                    10304
Montreal                   8641
Mexico City                8588
Helsinki                   8270
Roma                       8119
Tokyo                      7702
Moskva                     7191
Paris                      7169
Berlin                     6506
Amsterdam                  4992
Sochi                      4891
Melbourne                  4829
Vancouver                  4402
Torino                     4382
Stockholm                  4338
Antwerpen                  4292
Salt Lake City             4109
Innsbruck                  3639
Nagano                     3605
Albertville                3436
Lillehammer                3160
Calgary                    2639
Sarajevo

In [31]:
olympic_data['Sexo'].value_counts()

M    196594
F     74522
Name: Sexo, dtype: int64

In [35]:
olympic_data.describe()

ID          Idade         Height         Weight  \
count  271116.000000  261642.000000  210945.000000  208241.000000   
mean    68248.954396      25.556898     175.338970      70.702393   
std     39022.286345       6.393561      10.518462      14.348020   
min         1.000000      10.000000     127.000000      25.000000   
25%     34643.000000      21.000000     168.000000      60.000000   
50%     68205.000000      24.000000     175.000000      70.000000   
75%    102097.250000      28.000000     183.000000      79.000000   
max    135571.000000      97.000000     226.000000     214.000000   

                Year  
count  271116.000000  
mean     1978.378480  
std        29.877632  
min      1896.000000  
25%      1960.000000  
50%      1988.000000  
75%      2002.000000  
max      2016.000000

In [38]:
olympic_data.describe?

In [ ]:
.describe