In [1]:
import numpy as np

In [3]:
x = np.zeros(10)
x

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [5]:
np.size(x)

10

In [7]:
np.reshape(x, (10,1))

array([[0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.]])

In [9]:
z = np.linspace(2, 10, 20)
z

array([ 2.        ,  2.42105263,  2.84210526,  3.26315789,  3.68421053,
        4.10526316,  4.52631579,  4.94736842,  5.36842105,  5.78947368,
        6.21052632,  6.63157895,  7.05263158,  7.47368421,  7.89473684,
        8.31578947,  8.73684211,  9.15789474,  9.57894737, 10.        ])

In [12]:
z = np.array([10,20])
z

array([10, 20])

In [18]:
list = [3, 4, 5, 6, 2, 1, 4]
y = np.array((list))
print(y)
print(f"Sorted list{np.sort(y)}")

[3 4 5 6 2 1 4]
Sorted list[1 2 3 4 4 5 6]


In [24]:
list2 = [[1, 2, 3], [10,20,30], [50, 1, 2]]
a = np.array(list2)
print(a)

[[ 1  2  3]
 [10 20 30]
 [50  1  2]]


In [28]:
print(np.shape(a))
a.shape

(3, 3)


(3, 3)

In [33]:
np.random.seed(0)
z1 = np.random.randint(10, size=6)
z1

array([5, 0, 3, 3, 7, 9])

In [38]:
np.random.seed(0)
z1 = np.random.randint(10, size=(6,6))
z1

array([[5, 0, 3, 3, 7, 9],
       [3, 5, 2, 4, 7, 6],
       [8, 8, 1, 6, 7, 7],
       [8, 1, 5, 9, 8, 9],
       [4, 3, 0, 3, 5, 0],
       [2, 3, 8, 1, 3, 3]])

In [55]:
print(z1)
print(np.sum(z1)) #soma
print(np.prod(z1, axis=0)) #Return the product of array elements over a given axis.
print(np.mean(z1)) #média
print(np.std(z1)) #desvio padrão
print(np.var(z1)) #variance
print(np.min(z1)) # valor mínimo
print(np.max(z1)) # valor máximo
print(np.argmin(z1, axis = 0)) #posição do array com o menor valor// np.argmin(a, axis=None, out=None)
print(np.argmax(z1, axis = 1)) # Posição do array com maior valor // np.argmax(a, axis=None, out=None)

[[5 0 3 3 7 9]
 [3 5 2 4 7 6]
 [8 8 1 6 7 7]
 [8 1 5 9 8 9]
 [4 3 0 3 5 0]
 [2 3 8 1 3 3]]
166
[ 7680     0     0  1944 41160     0]
4.611111111111111
2.791632116978025
7.79320987654321
0
9
[5 0 4 5 5 4]
[5 4 0 3 4 2]


---

In [56]:
z2 = np.array([1, 2, 3, 4, 5])

In [59]:
z2 > 3

array([False, False, False,  True,  True])

In [60]:
z2 < 3

array([ True,  True, False, False, False])

In [63]:
z2[z2 > 3] # the array position with value > 3

array([4, 5])

----

In [64]:
a_array = np.array([1, 2, 3, 4, 5])
b_array = np.array([6, 7, 8, 9, 10])

In [70]:
a_array + b_array

array([ 7,  9, 11, 13, 15])

In [71]:
a_array * b_array

array([ 6, 14, 24, 36, 50])

In [66]:
a_array + 30

array([31, 32, 33, 34, 35])

In [67]:
a_array * 30

array([ 30,  60,  90, 120, 150])

In [73]:
a_array @ b_array # the product of the two arrays

130

In [80]:
np.sum(a_array * b_array) # is equal to the cell above

130

In [82]:
z1

array([[5, 0, 3, 3, 7, 9],
       [3, 5, 2, 4, 7, 6],
       [8, 8, 1, 6, 7, 7],
       [8, 1, 5, 9, 8, 9],
       [4, 3, 0, 3, 5, 0],
       [2, 3, 8, 1, 3, 3]])

In [85]:
np.sort(z1, axis=0)

array([[2, 0, 0, 1, 3, 0],
       [3, 1, 1, 3, 5, 3],
       [4, 3, 2, 3, 7, 6],
       [5, 3, 3, 4, 7, 7],
       [8, 5, 5, 6, 7, 9],
       [8, 8, 8, 9, 8, 9]])